FROM 727613293961.dkr.ecr.ap-southeast-1.amazonaws.com/ubuntu-php8:dev-php83

ENV USER 1001
ENV NON_ROOT_USER nginx
ENV PROJECTDIR /usr/share/nginx/html/pea-web-monitor

RUN apt update && apt upgrade -y && \
    apt-get install -y nodejs npm libnginx-mod-http-headers-more-filter && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# # Set Memory limit to 2048M
# RUN sed -i 's/memory_limit = 256M/memory_limit = 2048M/g' /etc/php/8.3/fpm/php.ini && \
#     sed -i 's/max_execution_time = 30/max_execution_time = 300/g' /etc/php/8.3/fpm/php.ini && \
#     sed -i 's/max_input_time = 60/max_input_time = 300/g' /etc/php/8.3/fpm/php.ini

# # Replace the values in www.conf
# RUN sed -i 's/^pm\s*=\s*dynamic/pm = ondemand/' /etc/php/8.3/fpm/pool.d/www.conf && \
#     sed -i 's/^pm\.max_children\s*=.*/pm.max_children = 100/' /etc/php/8.3/fpm/pool.d/www.conf && \
#     sed -i 's/^\s*;pm\.process_idle_timeout\s*=\s*10s/pm.process_idle_timeout = 10s/' /etc/php/8.3/fpm/pool.d/www.conf && \
#     sed -i 's/^\s*;pm\.max_requests\s*=\s*200/pm.max_requests = 100/' /etc/php/8.3/fpm/pool.d/www.conf

# Prepend the load_module directive to the Nginx configuration
RUN sed -i '1iload_module modules/ngx_http_headers_more_filter_module.so;' /etc/nginx/nginx.conf

# Copy project files
WORKDIR $PROJECTDIR/
COPY . .
RUN composer install --no-interaction --no-scripts --no-suggest --no-dev && \
    chmod -R 775 bootstrap/cache

# Temp remove package-lock.json and node_modules to fix x64 install issue
RUN rm -r package-lock.json && \
    npm install && \
    npm run build 

#Do a symlink
RUN if [ -d storage ]; then \
        rm -rf storage; \
        fi
RUN ln -sf /efs-laravel-storage storage

#Copy project nginx config
COPY dev-pea-web-monitor.conf /etc/nginx/conf.d/
COPY .env-develop $PROJECTDIR/.env

#Change own to nginx user
RUN chown -R $USER:$USER . && \
    chown -R $USER:$USER /var/cache/nginx && \
    chown -R $USER:$USER /var/log/nginx && \
    chown -R $USER:$USER /etc/nginx/conf.d && \
    chown -R $USER:$USER /etc/nginx && \
    chown -R $USER:$USER /var/lib/nginx
RUN touch /var/log/php-fpm.log && \
    chown -R $USER:$USER /var/log/php-fpm.log
RUN touch /var/run/nginx.pid && \
    chown -R $USER:$USER /var/run/nginx.pid && \
    chown -R $USER:$USER /etc/php/8.3/fpm/pool.d/www.conf && \
    chown -R $USER:$USER /run/php/

USER $USER
EXPOSE 8080
EXPOSE 443
ENTRYPOINT ["/start.sh"]